### ISSUE TITLE
email are not converted into ticket if sent from web form

### ISSUE THREAD

**Issue by MadBuddha** [uvdesk/mailbox-component#65] opened 2021-02-24 11:21 UTC
**Description**  
Email is imported but doesn't get converted to ticket.

Example of email submited by website form(non-UVDesk webform):

From: webform@mywebsite.com
To: techsupport@mywebsite.com

<user details and message>

techsupport@mywebsite.com is a mailbox.
The Import from techsupport@mywebsite.com runs smoothly, the email is there, console says it was converted to ticket.
When I check the tickets, the ticket is not there.

**How to reproduce**  
Use a contact us web form (non-UVDesk), import the email.

**Comment by jmrventura92** [comment] 2021-02-24 11:57
I did `dump(curl_error($curlHandler)); die;`  on pushMessage and got empty string

**Comment by papnoisanjeev** [comment] 2021-02-24 12:41
@jmrventura92 

Is your **site_url** is correct in **uvdesk.yaml**(under **config/packages** of your project) file ?

**Comment by jmrventura92** [comment] 2021-02-24 12:44
> @jmrventura92
> 
> Is your **site_url** is correct in **uvdesk.yaml**(under **config/packages** of your project) file ?

Hello :)

Yes it is. I'm able to import and convert to tickets emails that are sent directly. Works smoothly, no issues.
The problem is when the email doesn't come from the user himself but my web form.

**Comment by jmrventura92** [comment] 2021-02-24 12:48
**Working Example:**

From: user@gmail.com
To: techshupport@mywebsite.com


**Non-working Example:**

From: webform@mywebsite.com
To: techsupport@mywebsite.com


Note: In both examples "techsupport@mywebsite.com" is set as mailbox and it's where I run the import and convert command.

**Comment by papnoisanjeev** [comment] 2021-02-24 12:50
@jmrventura92 
> > @jmrventura92
> > Is your **site_url** is correct in **uvdesk.yaml**(under **config/packages** of your project) file ?
> 
> Hello :)
> 
> Yes it is. I'm able to import and convert to tickets emails that are sent directly to the email adress. Works smoothly, no issues.
> The problem is when the email doesn't come from the user himself but it was submited via web form. In this case my "FROM" email is not the user, but [myemail@mywebsite.com](mailto:myemail@mywebsite.com)

Ok we will check for indirect emails (in case of web) as well.

**Comment by jmrventura92** [comment] 2021-02-24 12:52
Thank you for your time papnoisanjeev

**Comment by jmrventura92** [comment] 2021-02-24 15:58
If there's anything I can help you with, let me know

**Comment by papnoisanjeev** [comment] 2021-04-01 09:34
@MadBuddha 

Locate path in your project:
vendor/uvdesk/mailbox-component/Services/MailboxService.php

Open **MailboxService.php** and replace its code from [here](https://github.com/uvdesk/mailbox-component/blob/master/Services/MailboxService.php).

We are closing it now if still facing you can reopen it.

**Closed by papnoisanjeev** 2021-04-01 09:34 UTC
